# Generated by Django 2.2.5 on 2021-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
